(require-package 'paredit)

(add-hook 'emacs-lisp-mode-hook (lambda ()
                                  (show-paren-mode 1)
                                  (turn-on-eldoc-mode)
                                  (paredit-mode)
                                  (auto-complete-mode)
                                  (local-set-key (kbd "C-c s") 'elisp-index-search)))

(add-hook 'lisp-interaction-mode-hook (lambda ()
                                        (add-to-list 'ac-sources 'ac-source-variables)
                                        (add-to-list 'ac-sources 'ac-source-symbols)
                                        (add-to-list 'ac-sources 'ac-source-functions)
                                        (add-to-list 'ac-sources 'ac-source-features)
                                        (auto-complete-mode)
                                        ))
(add-hook 'ielm-mode-hook (lambda ()
                            (add-to-list 'ac-sources 'ac-source-variables)
                            (add-to-list 'ac-sources 'ac-source-symbols)
                            (add-to-list 'ac-sources 'ac-source-functions)
                            (add-to-list 'ac-sources 'ac-source-features)
                            (auto-complete-mode)
                            (eldoc-mode)
                            ))

(provide 'init-lisp)
